name: P3TERXUbuntu
on:
  watch:
    types: started
  workflow_dispatch: # Put here!!
jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: SSH connection to Actions
      uses: P3TERX/debugger-action@master
